"""Ladder-template tooling package."""

from .core import (
    LadderTemplateAnnotation,
    LadderTemplateCell,
    LadderTemplateGrid,
    LadderTemplateImageOverlay,
    LadderTemplateMetadata,
    MaterializedLadderTemplate,
    ladder_template_annotation_from_dict,
    load_ladder_template_annotation,
    materialize_ladder_template,
)
from .data_targets import (
    LadderExampleMatch,
    LadderExampleTarget,
    build_ladder_certificate_target_for_training_example,
    find_ladder_matches_for_training_example,
    resolve_last_move_for_training_example,
)
from .labeler import (
    LadderCertificateLabels,
    build_ladder_certificate_labels,
    ladder_certificate_plane_index,
    ladder_certificate_plane_names,
    ladder_certificate_plane_specs,
)
from .library_loader import (
    LoadedLadderTemplate,
    build_loaded_ladder_template,
    default_hexwiki_generated_library_dir,
    infer_row_class_from_template_name,
    iter_templates_for_row_class,
    load_hexwiki_generated_ladder_templates,
    load_ladder_template_library,
)
from .matcher import (
    LadderMatchResult,
    LadderMatchStats,
    LadderTemplateMatch,
    find_ladder_template_matches,
    normalize_board_for_ladder_matching,
    transform_board_long_diagonal_color_swap,
)
from .sequence_labeler import (
    LadderGameLabelSequence,
    LadderSequencePositionStats,
    build_ladder_certificate_label_sequence_for_trmph_game,
)
from .sidecar import (
    LADDER_CERTIFICATE_MAP_ENCODING_DENSE_U8_ZLIB_BASE64,
    LADDER_CERTIFICATE_SIDECAR_SCHEMA_VERSION,
    LadderCertificateSidecarRecord,
    build_ladder_certificate_sidecar_record_for_trmph_game,
    build_ladder_certificate_sidecar_records_for_trmph_file,
    decode_ladder_certificate_maps_blob,
    encode_ladder_certificate_maps_blob,
    extract_trmph_games_for_ladder_sidecar,
    ladder_certificate_sidecar_path_for_trmph,
    load_ladder_certificate_sidecar,
    write_ladder_certificate_sidecar,
)
from .prefill_geometry import (
    DetectedImageCell,
    InferredGridGeometry,
    InferredTemplateCell,
    build_prefill_annotation_payload,
    infer_offset_grid,
)

__all__ = [
    "DetectedImageCell",
    "InferredGridGeometry",
    "InferredTemplateCell",
    "LadderCertificateLabels",
    "LadderCertificateSidecarRecord",
    "LadderExampleMatch",
    "LadderExampleTarget",
    "LadderGameLabelSequence",
    "LadderMatchResult",
    "LadderMatchStats",
    "LadderSequencePositionStats",
    "LadderTemplateAnnotation",
    "LadderTemplateCell",
    "LadderTemplateGrid",
    "LadderTemplateImageOverlay",
    "LadderTemplateMetadata",
    "LadderTemplateMatch",
    "LoadedLadderTemplate",
    "MaterializedLadderTemplate",
    "build_ladder_certificate_labels",
    "build_ladder_certificate_label_sequence_for_trmph_game",
    "build_ladder_certificate_sidecar_record_for_trmph_game",
    "build_ladder_certificate_sidecar_records_for_trmph_file",
    "build_ladder_certificate_target_for_training_example",
    "build_loaded_ladder_template",
    "build_prefill_annotation_payload",
    "decode_ladder_certificate_maps_blob",
    "default_hexwiki_generated_library_dir",
    "encode_ladder_certificate_maps_blob",
    "extract_trmph_games_for_ladder_sidecar",
    "find_ladder_template_matches",
    "find_ladder_matches_for_training_example",
    "infer_offset_grid",
    "infer_row_class_from_template_name",
    "iter_templates_for_row_class",
    "ladder_certificate_sidecar_path_for_trmph",
    "ladder_certificate_plane_index",
    "ladder_certificate_plane_names",
    "ladder_certificate_plane_specs",
    "ladder_template_annotation_from_dict",
    "load_ladder_certificate_sidecar",
    "load_hexwiki_generated_ladder_templates",
    "load_ladder_template_library",
    "load_ladder_template_annotation",
    "materialize_ladder_template",
    "normalize_board_for_ladder_matching",
    "resolve_last_move_for_training_example",
    "transform_board_long_diagonal_color_swap",
    "write_ladder_certificate_sidecar",
    "LADDER_CERTIFICATE_MAP_ENCODING_DENSE_U8_ZLIB_BASE64",
    "LADDER_CERTIFICATE_SIDECAR_SCHEMA_VERSION",
]
